apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
      deployment: blue
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: backend
        deployment: blue
    spec:
      containers:
        - name: backend-blue
          image: mstar228/techup-backend:latest
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: backend-cm
                  key: AWS_REGION
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-cm
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-cm
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-cm
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: KAKAO_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: backend-secret
                  key: KAKAO_CLIENT_ID
            - name: KAKAO_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-secret
                  key: KAKAO_REDIRECT_URI
            - name: PORTONE_CHANNEL_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-secret
                  key: PORTONE_CHANNEL_KEY
            - name: PORTONE_SECRET
              valueFrom:
                configMapKeyRef:
                  name: backend-secret
                  key: PORTONE_SECRET
            - name: PORTONE_STOREID
              valueFrom:
                configMapKeyRef:
                  name: backend-secret
                  key: PORTONE_STOREID
            - name: MAIL_ADDR
              valueFrom:
                configMapKeyRef:
                  name: backend-secret
                  key: MAIL_ADDR
            - name: MAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-secret
                  key: MAIL_PASSWORD
            - name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-secret
                  key: AWS_SECRET_KEY
            - name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: backend-cm
                  key: AWS_S3_BUCKET
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: backend-secret
                  key: JWT_EXPIRATION
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-cm
                  key: ELASTIC_HOST
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-cm
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-cm
                  key: REDIS_PORT

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-cluster
                  key: redis-password


          ports:
            - containerPort: 8080
      terminationGracePeriodSeconds: 0