apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-recommender
  labels:
    app: product-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-recommender
  template:
    metadata:
      labels:
        app: product-recommender
    spec:
      containers:
      - name: product-recommender
        image: mstar228/techup-recommend:2.0
        ports:
        - containerPort: 8000